### ISSUE TITLE
IP addresses for snowflake-02 bridge

### ISSUE THREAD

**Issue by uumaro** [Enkidu-6/tor-relay-lists#2]
There is now a second Snowflake bridge, released with [Tor Browser 12.0](https://blog.torproject.org/new-release-tor-browser-120/). At this point its outbound address is the same as the forward DNS record for snowflake-02.torproject.net, and there is just one IP address each for IPv4 and IPv6.

```
141.212.118.18
2607:f018:600:8:be30:5bff:fef1:c6fa
```

Related to https://github.com/Enkidu-6/tor-ddos/issues/25 (multiple IP addresses for snowflake-01 bridge).

Cf. https://github.com/toralf/torutils/commit/6bd1940b10bde0f328d2f4a67df117b4a7f74d1a.

**Comment by Enkidu-6** [comment]
Added to the source list where scripts pull the addresses from. Users will have the new allow-list the next time they run the cron job or they can simply run [refresh-authorities.sh](https://raw.githubusercontent.com/Enkidu-6/tor-ddos/main/cron/refresh-authorities.sh) to add it to the list immediately.
